# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - bnbapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_PORT: ${{ env.PORT }}
          envkey_HOST_NAME: ${{ env.HOST_NAME }}
          envkey_DB_USER: ${{ env.DB_USER }}
          envkey_DB_PASS: ${{ env.DB_PASS }}
          envkey_DB_PASSWORD: ${{ env.DB_PASSWORD }}
          envkey_DB_HOST: ${{ env.DB_HOST }}
          envkey_DB_PORT: ${{ env.DB_PORT }}
          envkey_DB_DATABASE: ${{ env.DB_DATABASE }}
          envkey_SECRET_KEY: ${{ env.SECRET_KEY }}
          envkey_LOG_FORMAT: ${{ env.LOG_FORMAT }}
          envkey_LOG_DIR: ${{ env.LOG_DIR }}
          envkey_TEST_TOKEN: ${{ env.TEST_TOKEN }}
          envkey_ORIGIN: ${{ env.ORIGIN }}
          envkey_CREDENTIALS: ${{ env.CREDENTIALS }}
          file_name: .env.test

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bnbapi'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2899E4C07C944810B0DB34DF1C3BE938 }}
